### ISSUE TITLE
Congratulation to your AutoKaggle

### ISSUE THREAD

**Issue by LiqiangJing** [multimodal-art-projection/AutoKaggle#2]
Hi,
Congrats on the impressive work. Our work DSBench (DSBench: How Far are Data Science Agents from Becoming Data Science Experts?) is very related to your work. If you don't mind, you can consider citing our paper.

Thank you!

**Comment by azusa-li** [comment]
Thank you for your attention and recognition! DSBench is highly relevant to our work. I apologize for not citing your work in the previous submission - I have now added the citation.

**Comment by LiqiangJing** [comment]
Thanks!
