### ISSUE TITLE
Is there any baselines for comparison?

### ISSUE THREAD

**Issue by waltonfuture** [multimodal-art-projection/AutoKaggle#3]
It seems that I can’t find some related baselines for comparison in your experiments. It is helpful if we can learn more related methods around this task. Thanks.

**Comment by azusa-li** [comment]
Thank you for your interest! In our paper, we conducted a comparison with the AIDE framework (https://github.com/WecoAI/aideml), which has shown excellent performance in MLE-Bench. In our evaluated tasks, AutoKaggle demonstrated better performance in both valid submission rates and comprehensive scores.

**Comment by waltonfuture** [comment]
thanks for your response! this helps me learn more related projects about such tasks. btw, I think comparing your framework with more baselines can make your work more solid :)

**Comment by azusa-li** [comment]
Thank you for your valuable suggestion! We will consider updating in the second edition of AutoKaggle, please stay tuned!

**Comment by waltonfuture** [comment]
thanks! Hope that you can remind me if updated :)
